branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: django-first-app-env
    group_suffix: null
environment-defaults:
  django-first-app--env:
    branch: null
    repository: null
global:
  application_name: django-first-app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.11
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
